# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c698e9c30dc0662b9fb3d51c5a24c6df146adebcc65be1b9a79ec4fcba41cc220e96121afcd4bbbeb3e28d42fb834faa439e9ef0332a5052648c49b4b0b70b

test:
  secret_key_base: 51569700ba97b39817544c1e25f32c9d0be56b81995b5d0bf784f58c5e6b2827b40fdc7e7fae721823e29e05ff086bdea2167ff28ca63aaa569a3dffa43a129e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
